title: Chua Chu Kang Primary School
url: https://www.chuachukangpri.moe.edu.sg
favicon: /images/CCK-Logo-b-colour-200.png
colors:
  primary-color: "#2b49a4"
  secondary-color: "#2b49a4"
  media-colors:
    - title: media-color-one
      color: "#cf6837"
    - title: media-color-two
      color: "#2b49a4"
    - title: media-color-three
      color: "#2b49a4"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2r6ojvhiiw1qc.amplifyapp.com
prod: https://master.d2r6ojvhiiw1qc.amplifyapp.com
shareicon: /images/CCK-Logo-b-colour-200.png
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
resources_name: announcements
google_analytics_ga4: G-R362JCZKB8
